/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-variant': 'var(--color-surface-container-highest)',
        'surface-tint': '#c6c6c7',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-on-surface)',
        'inverse-on-surface': 'var(--color-surface-container-high)',
        outline: '#8e9192',
        'outline-variant': 'var(--color-outline-variant)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': '#636565',
        'inverse-primary': '#5d5f5f',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c7',
        'on-primary-fixed': '#1a1c1c',
        'on-primary-fixed-variant': '#454747',
        secondary: '#b9c8de',
        'on-secondary': '#233143',
        'secondary-container': '#39485a',
        'on-secondary-container': '#a7b6cc',
        'secondary-fixed': '#d4e4fa',
        'secondary-fixed-dim': '#b9c8de',
        'on-secondary-fixed': '#0d1c2d',
        'on-secondary-fixed-variant': '#39485a',
        tertiary: '#ffffff',
        'on-tertiary': '#233144',
        'tertiary-container': '#d5e3fd',
        'on-tertiary-container': '#57657b',
        'tertiary-fixed': '#d5e3fd',
        'tertiary-fixed-dim': '#b9c7e0',
        'on-tertiary-fixed': '#0d1c2f',
        'on-tertiary-fixed-variant': '#3a485c',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: 'var(--color-surface)',
        'on-background': 'var(--color-on-surface)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'stack-gap-sm': '8px',
        'stack-gap-md': '16px',
        'stack-gap-lg': '32px',
      },
      maxWidth: {
        'container-max-width': '1440px',
      },
      fontFamily: {
        'display-xl': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-xl-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        'code-sm': ['Geist', 'monospace'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { opacity: '0.1' },
          '50%': { opacity: '0.25' },
        },
        'pulse-dot': {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.5', transform: 'scale(0.8)' },
        },
      },
      animation: {
        'pulse-glow': 'pulse-glow 4s infinite cubic-bezier(0.4, 0, 0.6, 1)',
        'pulse-dot': 'pulse-dot 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
